name: Maven Build Artifact

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        required: false
        default: "21"
        type: string
      java-distribution:
        description: 'Java distribution'
        required: false
        default: "temurin"
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install thrift
        uses: valitydev/action-setup-thrift@v0.0.6

      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: 'maven'

      - name: Build packages
        run: mvn -B clean verify
