name: Maven Deploy Artifact

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        required: false
        default: "21"
        type: string
      java-distribution:
        description: 'Java distribution'
        required: false
        default: "temurin"
        type: string
    secrets:
      mm-webhook-url:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: 'maven'

      - name: Set up buf action
        uses: bufbuild/buf-setup-action@v1.11.0
        with:
          version: 1.11.0
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Running linter
        run: |
          buf lint

      - name: Extract mvn project info
        id: info
        uses: ./.github/actions/mvn-project-info

      - name: Delete SNAPSHOT versions with branch suffix
        if: env.BRANCH_SUFFIX != ''
        uses: actions/github-script@v7
        env:
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
          REPOSITORY_OWNER: ${{ env.REPOSITORY_OWNER }}
          BRANCH_SUFFIX: ${{ env.BRANCH_SUFFIX }}
        with:
          script: |
            const fn = require('./scripts/deleteSnapshots.js');
            await fn({ github, core });

      - name: Deploy artifact
        run: |
          mvn -B clean deploy -Drevision=${{ env.REVISION }}
        env:
          REVISION: ${{ env.REVISION }}
          GITHUB_TOKEN: ${{ secrets.github-token }}

  notify:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Mattermost Notification
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_USERNAME: ${{ github.event.repository.name }}
          SLACK_WEBHOOK: ${{ secrets.mm-webhook-url }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_LINK_NAMES: true
          SLACK_FOOTER: ""
