name: Maven Deploy Artifact

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        required: false
        default: "21"
        type: string
      java-distribution:
        description: 'Java distribution'
        required: false
        default: "temurin"
        type: string
    secrets:
      mm-webhook-url:
        required: true
      github-user:
        required: true
      github-pat:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: 'maven'

      - name: Generate Maven settings.xml
        shell: bash
        run: bash ./scripts/generate-settings.sh
        env:
          GITHUB_USER: ${{ secrets.github-user }}
          GITHUB_PAT: ${{ secrets.github-pat }}

      - name: Cache local Maven repository
        id: mvn-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.HOME }}/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Extract mvn project info
        id: info
        uses: ./.github/actions/mvn-project-info

      - name: Deploy artifact
        run: |
          mvn -B clean deploy
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          REVISION: ${{ env.REVISION }}
          COMMIT_NUMBER: ${{ env.COMMIT_NUMBER }}

  notify:
    runs-on: ubuntu-22.04
    needs: [deploy]
    steps:
      - name: Mattermost Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_USERNAME: ${{ github.event.repository.name }}
          SLACK_WEBHOOK: ${{ secrets.mm-webhook-url }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_LINK_NAMES: true
          SLACK_FOOTER: ""
