name: Maven Build Artifact

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node version'
        required: false
        default: "16"
        type: string
      java-version:
        description: 'Java version'
        required: false
        default: "17"
        type: string
      java-distribution:
        description: 'Java distribution'
        required: false
        default: "temurin"
        type: string
      run-script-name:
        description: ''
        required: true
        default: "build"
        type: string

jobs:
  bundle:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: NPM install
        run: npm install

      - name: Bundle specification
        run: npm run ${{ inputs.run-script-name }}

      - name: Validate specification
        run: npm run validate

      - name: Build server jar
        run: mvn --batch-mode clean package site -f pom.xml -P="server"

      - name: Build client jar
        run: mvn --batch-mode clean package site -f pom.xml -P="client"
        
      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: bom.json
          path: 'target/bom.json'
  scan:
    name: Vuln Scan with Trivy
    needs: bundle
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Install Trivy CLI
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.39.1/trivy_0.39.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.39.1_Linux-64bit.deb
      - uses: actions/download-artifact@v3
        with:
          name: bom.json
      - name: Run Trivy with SBOM
        run: trivy sbom --exit-code 1 --severity CRITICAL,HIGH ./bom.json
