name: Maven Build Artifact

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        required: false
        default: "17"
        type: string
      java-distribution:
        description: 'Java distribution'
        required: false
        default: "temurin"
        type: string
      mvn-args:
        description: 'Additional maven args'
        required: false
        default: "site"
        type: string
    secrets:
      action-fetch-token:
        required: true
      github-pkg-ro-pat:
        required: true
      github-pkg-ro-user:
        required: true
      mm-sa-wh-url:
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Checkout GitHub Action JDK Build Repo
        uses: actions/checkout@v4
        with:
          repository: empayre/action-jdk-build
          ref: v1.0.19
          token: ${{ secrets.action-fetch-token }}
          path: .github/actions/action-jdk-build

      - name: Run Build Java
        uses: ./.github/actions/action-jdk-build
        with:
          github-pat: ${{ secrets.github-pkg-ro-pat }}
          github-user: ${{ secrets.github-pkg-ro-user }}
          mvn-args: ${{ inputs.mvn-args }}
          jdk-version: ${{ inputs.java-version }}
          jdk-distribution: ${{ inputs.java-distribution }}
  scan:
    name: Vulnerabilities
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Install Trivy CLI
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.54.1/trivy_0.54.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.54.1_Linux-64bit.deb

      - uses: actions/download-artifact@v3
        with:
          name: bom.json

      - name: Run Trivy with SBOM
        run: trivy sbom --severity CRITICAL,HIGH --format table -o trivy-report.json ./bom.json

      - name: Display in the console
        run: |
          cat trivy-report.json

      - name: Mattermost Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_USERNAME: ${{ github.event.repository.name }}
          SLACK_WEBHOOK: ${{ secrets.mm-sa-wh-url }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_LINK_NAMES: true
          SLACK_FOOTER: ""  

      - name: Find and Update Comment with Trivy Results
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const trivyResults = fs.readFileSync('trivy-report.json', 'utf8');
            const pr_number = context.payload.pull_request.number;
        
            const comments = await github.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr_number,
              });
          
            const existingComment = comments.data.find(comment => comment.body.includes('Trivy analysis results:'));
            const formattedResults = `
                <details>
                  <summary>Trivy Analysis Results</summary>

                  <pre style="background-color: #F6F8FA; color: black; padding: 10px; border-radius: 6px;">
                ${trivyResults}
                  </pre>
                </details>
                      `;
            if (existingComment) {
                await github.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: existingComment.id,
                  body: formattedResults,
                });
              } else {
                await github.issues.createComment({
                  issue_number: pr_number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: formattedResults,
                });
              }   