name: Maven Build Artifact

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        required: false
        default: "17"
        type: string
      java-distribution:
        description: 'Java distribution'
        required: false
        default: "temurin"
        type: string
      mvn-args:
        description: 'Additional maven args'
        required: false
        type: string
    secrets:
      action-fetch-token:
        required: true
      github-pkg-ro-pat:
        required: true
      github-pkg-ro-user:
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Checkout GitHub Action JDK Build Repo
        uses: actions/checkout@v3
        with:
          repository: empayre/action-jdk-build
          ref: v1.0.18
          token: ${{ secrets.action-fetch-token }}
          path: .github/actions/action-jdk-build

      - name: Run Build Java
        uses: ./.github/actions/action-jdk-build
        with:
          github-pat: ${{ secrets.github-pkg-ro-pat }}
          github-user: ${{ secrets.github-pkg-ro-user }}
