name: Maven Build Artifact

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        required: false
        default: "21"
        type: string
      java-distribution:
        description: 'Java distribution'
        required: false
        default: "temurin"
        type: string
      mvn-args:
        description: 'Additional maven args'
        required: false
        type: string
    secrets:
      action-fetch-token:
        required: true
      github-user:
        required: true
      github-pat:
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Checkout GitHub Action JDK Build Repo
        uses: actions/checkout@v4
        with:
          repository: empayre/action-jdk-build
          ref: v1.0.24
          token: ${{ secrets.action-fetch-token }}
          path: .github/actions/action-jdk-build
          fetch-depth: 0
          fetch-tags: true

      - name: Run Build Java
        uses: ./.github/actions/action-jdk-build
        with:
          github-pat: ${{ secrets.github-user }}
          github-user: ${{ secrets.github-pat }}
          mvn-args: ${{ inputs.mvn-args }}
          jdk-version: ${{ inputs.java-version }}
          jdk-distribution: ${{ inputs.java-distribution }}