name: Maven Build Artifact

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        required: false
        default: "17"
        type: string
      java-distribution:
        description: 'Java distribution'
        required: false
        default: "temurin"
        type: string
      mvn-args:
        description: 'Additional maven args'
        required: false
        type: string
    secrets:
      action-fetch-token:
        required: true
      github-pkg-ro-pat:
        required: true
      github-pkg-ro-user:
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Checkout GitHub Action JDK Build Repo
        uses: actions/checkout@v3
        with:
          repository: empayre/action-jdk-build
          ref: v1.0.19-alfa
          token: ${{ secrets.action-fetch-token }}
          path: .github/actions/action-jdk-build

      - name: Run Build Java
        uses: ./.github/actions/action-jdk-build
        with:
          github-pat: ${{ secrets.github-pkg-ro-pat }}
          github-user: ${{ secrets.github-pkg-ro-user }}
          mvn-args: ${{ inputs.mvn-args }}
          jdk-version: ${{ inputs.java-version }}
          jdk-distribution: ${{ inputs.java-distribution }}
  scan:
    name: Vulnerabilities
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Trivy CLI
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.39.1/trivy_0.39.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.39.1_Linux-64bit.deb
      - uses: actions/download-artifact@v3
        with:
          name: bom.json
      - name: Run Trivy with SBOM
        run: trivy sbom --exit-code 1 --severity CRITICAL,HIGH ./bom.json
