name: Maven Deploy Artifact

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        required: false
        default: "17"
        type: string
      java-distribution:
        description: 'Java distribution'
        required: false
        default: "temurin"
        type: string
      mvn-args:
        description: 'Additional maven args'
        required: false
        type: string
    secrets:
      mm-webhook-url:
        required: true
      action-fetch-token:
        required: true
      github-pkg-ro-pat:
        required: true
      github-pkg-ro-user:
        required: true
      aws-ecr-access_key:
        required: true
      aws-ecr-secret-key:
        required: true
      aws-region:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Checkout GitHub Action JDK Build Repo
        uses: actions/checkout@v3
        with:
          repository: empayre/action-jdk-build
          ref: v1.0.17
          token: ${{ secrets.action-fetch-token }}
          path: .github/actions/action-jdk-build

      - name: Checkout GitHub Action Deploy Docker Repo
        uses: actions/checkout@v3
        with:
          repository: empayre/action-deploy-docker
          ref: v2.0.0
          token: ${{ secrets.action-fetch-token }}
          path: .github/actions/action-deploy-docker

      - name: Run Build Java
        uses: ./.github/actions/action-jdk-build
        with:
          github-pat: ${{ secrets.github-pkg-ro-pat }}
          github-user: ${{ secrets.github-pkg-ro-user }}

      - name: Deploy image
        uses: ./.github/actions/action-deploy-docker
        with:
          aws-ecr-access-key: ${{ secrets.aws-ecr-access_key }}
          aws-ecr-secret-key: ${{ secrets.aws-ecr-secret-key }}
          aws-region: ${{ secrets.aws-region }}

      - name: Mattermost Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_USERNAME: ${{ github.event.repository.name }}
          SLACK_WEBHOOK: ${{ secrets.mm-webhook-url }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_LINK_NAMES: true
          SLACK_FOOTER: ""