name: Run Semgrep
on:
  workflow_call:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: | 
          semgrep \
            --json --output semgrep.json \
            --metrics=off \
            --config="p/default"

      - name: convert
        run: |
          python \
          import json
          # Load the JSON file
          with open('semgrep.json') as f:
              data = json.load(f)
          # Extract the required fields
          extracted_data = []
          for result in data.get('results', []):
              path = result.get('path')
              start = result.get('start')
              end = result.get('end')
              severity = result.get('extra', {}).get('severity')
              extracted_data.append({
                  'path': path,
                  'start': start,
                  'end': end,
                  'severity': severity
              })

      - name: save res in json
        run: |
          echo semgrep.json > results.json

      - name: Save report
        uses: actions/upload-artifact@v3
        with:
          name: convert-results
          path: results.json

      #- name: Scanning alerts
      #  uses: github/codeql-action/upload-sarif@v3.25.7
      #  with:
      #    sarif_file: semgrep.sarif
      #    category: semgrep