name: Run Semgrep
on:
  workflow_call:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: | 
          semgrep \
            --metrics=off \
            --config="p/default"

      - name: convert
        run: |
          semgrep --json | awk '{print "{\"path\": \"" $1 "\", \"start\": \"" $2 "\", \"end\": \"" $3 "\", \"severity\": \"" $4 "\"}"}' > parsed_results.json

      - name: Save report
        uses: actions/upload-artifact@v3
        with:
          name: convert-results
          path: results.json

      #- name: Scanning alerts
      #  uses: github/codeql-action/upload-sarif@v3.25.7
      #  with:
      #    sarif_file: semgrep.sarif
      #    category: semgrep