name: Run Semgrep
on:
  workflow_call:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: | 
          semgrep \
            --gitlab-sast --output semgrep.json\
            --metrics=off \
            --config="p/default"

      - name: Save report
        uses: actions/upload-artifact@v4
        with:
          name: parsed_results
          path: semgrep.json

      - name: Display in the console
        run: |
          cat semgrep.json | jq '.vulnerabilities[] | { category, description, location: { end_line, file, start_line }, severity }'
