name: Trivy

on:
  workflow_call:

jobs:
  generate_sbom_and_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install -g @cyclonedx/cdxgen

      - name: Generate SBOM
        run: |
          echo "Генерация SBOM..."
          cdxgen -t java -o bom.json

      - name: Scan SBOM for vulnerabilities
        run: |
          echo "Сканирование SBOM на наличие уязвимостей..."
          trivy sbom --exit-code 1 --severity CRITICAL,HIGH bom.json

      - name: Upload SARIF report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.sarif